
USE ZOO;

CREATE TABLE
    SPECIES (
        NAME VARCHAR(20),
        CATEGORY VARCHAR(20) NOT NULL,
        DESCRIPTION TEXT NOT NULL,
        PRIMARY KEY (NAME)
    );

CREATE TABLE ANIMAL(
    NAME VARCHAR(20) NOT NULL,
    CODE CHAR(8),
    YEAR_OF_BIRTH YEAR(4) NOT NULL,
    SPECIES_NAME VARCHAR(20) NOT NULL,
    PRIMARY KEY (CODE),
    FOREIGN KEY (SPECIES_NAME) REFERENCES SPECIES(NAME)
);


CREATE TABLE CARETAKER(
    NAME VARCHAR(20) NOT NULL,
    ID INT AUTO_INCREMENT,
    LAST_NAME VARCHAR(20) NOT NULL,
    PHONE VARCHAR(15) NOT NULL,
    PRIMARY KEY (ID)
);

